DROP TABLE TAREA_USUARIO;
DROP TABLE USUARIO;
DROP TABLE TAREA;

CREATE TABLE USUARIO(
	DNI VARCHAR(9),
	FECHA_ALTA DATETIME DEFAULT NOW(),
	NOMBRE VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(30) NOT NULL,
	DESCRIPCION VARCHAR(200),
	CARGO DECIMAL(1) NOT NULL,
	HORAS_ACUMULADAS VARCHAR(5),
	EMAIL VARCHAR(30) NOT NULL,
	CONSTRAINT PRIMARY KEY(DNI)
);

INSERT INTO USUARIO(DNI, NOMBRE, PASSWORD, DESCRIPCION, CARGO, HORAS_ACUMULADAS, EMAIL) VALUES('X62001111', 'ANDRIY', 'ANDRIY', 'HUEHUEHUE', 1, '320', 'ANDRIY@GMAIL.COM');

CREATE TABLE TAREA(
	ID INT AUTO_INCREMENT,
	FECHA_ALTA DATETIME NOT NULL DEFAULT NOW(),
	DESCRIPCION VARCHAR(255),
	FECHA_INICIO DATE NOT NULL,
	HORA_INICIO VARCHAR(5) NOT NULL,
	FECHA_FIN DATE NOT NULL,
	HORA_FIN VARCHAR(5) NOT NULL,
	HORAS_TAREA DECIMAL(4) NOT NULL,
	TOTAL_HORAS DECIMAL(4) NOT NULL,
	CONSTRAINT PRIMARY KEY(ID)
);

CREATE TABLE TAREA_USUARIO (
	ID_TAREA INT,
	DNI_USUARIO VARCHAR(9),
	HORAS DECIMAL(4) NOT NULL,
	LABOR VARCHAR(100) NOT NULL,
	CONSTRAINT PRIMARY KEY(ID_TAREA, DNI_USUARIO),
	CONSTRAINT FOREIGN KEY(ID_TAREA) REFERENCES TAREA(ID),
	CONSTRAINT FOREIGN KEY(DNI_USUARIO) REFERENCES USUARIO(DNI)
);