CREATE TABLE USUARIO(
	DNI VARCHAR(9),
	FECHA_ALTA DATETIME DEFAULT NOW(),
	NOMBRE VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(30) NOT NULL,
	DESCRIPCION VARCHAR(200),
	CARGO DECIMAL(1) NOT NULL,
	HORAS_ACUMULADAS VARCHAR(5),
	EMAIL VARCHAR(30) NOT NULL,
	CONSTRAINT PRIMARY KEY(DNI)
);

INSERT INTO USUARIO(DNI, NOMBRE, PASSWORD, DESCRIPCION, CARGO, HORAS_ACUMULADAS, EMAIL) VALUES('X62001111', 'ANDRIY', 'ANDRIY', 'HUEHUEHUE', 1, '320', 'ANDRIY@GMAIL.COM');
INSERT INTO USUARIO(DNI, NOMBRE, PASSWORD, DESCRIPCION, CARGO, HORAS_ACUMULADAS, EMAIL) 
	VALUES('DANI', 'DANI', 'DANI', 'DANIDANI', 2, '320', 'DANI@GMAIL.COM');
INSERT INTO USUARIO(DNI, NOMBRE, PASSWORD, DESCRIPCION, CARGO, HORAS_ACUMULADAS, EMAIL) 
	VALUES('ALBERTO', 'ALBERTO', 'ALBERTO', 'ALBERTOALBERTO', 2, '520', 'ALBERTO@GMAIL.COM');
INSERT INTO USUARIO(DNI, NOMBRE, PASSWORD, DESCRIPCION, CARGO, HORAS_ACUMULADAS, EMAIL) 
	VALUES('EMI', 'EMI', 'EMI', 'EMILIO', 3, '20', 'EMILIO@GMAIL.COM');
INSERT INTO USUARIO(DNI, NOMBRE, PASSWORD, DESCRIPCION, CARGO, HORAS_ACUMULADAS, EMAIL) 
	VALUES('RAFA', 'RAFA', 'RAFA', 'RAFAEL', 2, '220', 'RAFAEL@GMAIL.COM');

CREATE TABLE TAREA(
	ID INT AUTO_INCREMENT,
	FECHA_ALTA DATETIME DEFAULT NOW(),
	DESCRIPCION VARCHAR(255),
	FECHA_INICIO DATE NOT NULL,
	HORA_INICIO VARCHAR(5) NOT NULL,
	FECHA_FIN DATE NOT NULL,
	HORA_FIN VARCHAR(5) NOT NULL,
	HORAS_TAREA DECIMAL(4) NOT NULL,
	TOTAL_HORAS DECIMAL(4) NOT NULL,
	CONSTRAINT PRIMARY KEY(ID)
);

INSERT INTO TAREA(DESCRIPCION, FECHA_INICIO, HORA_INICIO, FECHA_FIN, HORA_FIN, HORAS_TAREA, TOTAL_HORAS) 
		   VALUES('TEST1', '1999-12-12', '12:00', '2999-12-12', '13:00', 500, 2000);

INSERT INTO TAREA(DESCRIPCION, FECHA_INICIO, HORA_INICIO, FECHA_FIN, HORA_FIN, HORAS_TAREA, TOTAL_HORAS) 
		   VALUES('TEST2', '1999-12-12', '12:00', '2999-12-12', '13:00', 500, 2000);
           
INSERT INTO TAREA(DESCRIPCION, FECHA_INICIO, HORA_INICIO, FECHA_FIN, HORA_FIN, HORAS_TAREA, TOTAL_HORAS) 
		   VALUES('TEST3', '1999-12-12', '12:00', '2999-12-12', '13:00', 500, 2000);
           
INSERT INTO TAREA(DESCRIPCION, FECHA_INICIO, HORA_INICIO, FECHA_FIN, HORA_FIN, HORAS_TAREA, TOTAL_HORAS) 
		   VALUES('TEST4', '1999-12-12', '12:00', '2999-12-12', '13:00', 500, 2000);

CREATE TABLE TAREA_USUARIO (
	ID_TAREA INT,
	DNI_USUARIO VARCHAR(9),
	HORAS DECIMAL(4) NOT NULL,
	LABOR VARCHAR(100) NOT NULL,
	CONSTRAINT PRIMARY KEY(ID_TAREA, DNI_USUARIO),
	CONSTRAINT FOREIGN KEY(ID_TAREA) REFERENCES TAREA(ID),
	CONSTRAINT FOREIGN KEY(DNI_USUARIO) REFERENCES USUARIO(DNI)
);

INSERT INTO TAREA_USUARIO(ID_TAREA, DNI_USUARIO, HORAS, LABOR)
					VALUES(1, 'HUEHUEHUE', 5, 'ESTILISTA');
INSERT INTO TAREA_USUARIO(ID_TAREA, DNI_USUARIO, HORAS, LABOR)
					VALUES(6, 'HUEHUEHUE', 5, 'ESTILISTA');
INSERT INTO TAREA_USUARIO(ID_TAREA, DNI_USUARIO, HORAS, LABOR)
					VALUES(1, 'X62001111', 5, 'BANK ROBBER');
INSERT INTO TAREA_USUARIO(ID_TAREA, DNI_USUARIO, HORAS, LABOR)
					VALUES(8, 'X62001111', 5, 'BANK ROBBER');